name: Re-Deployment

on:
  push:
    branches:
      - master

jobs:
  remote-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into VM and run remote commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "✅ Connected successfully to remote VM"
            ls -al
            if [ -d "Portfolio" ]; then
                echo "📦 Portfolio directory exists. Pulling latest changes..."
                cd Portfolio
                git pull origin master
                npm install
                pm2 restart all
            else
                echo "❌ Portfolio directory not found!"
            fi
          EOF
